Choose how already existing files are treated
ie3-institute/simbench4ie3 pull request #35
Opened 2020-09-03 11:45 UTC by ckittl

Closes #34

2020-09-14 11:24 UTC, johanneshiry requested changes

2020-09-14 11:24 UTC, johanneshiry commented on src/main/scala/edu/ie3/simbench/io/Downloader.scala
> +          logger.warn(
This warning is actually pointless, bc the moment the user reads it, its already too late. I would prefer throwing an exception but never ever delete files except if it is set explicitly in the config. I would still vote against such a config parameter as it is very dangerous. Better break the process here and ask the user to decide either to clean the folder or set another folder as target.

2020-09-15 12:20 UTC, ckittl commented on src/main/scala/edu/ie3/simbench/io/Downloader.scala
> +          logger.warn(
Actually, I really would like to keep this feature. From my point of view, the target folder of the files should only be seen as something temporary. If one achieved valuable results he  or she should make sure to move them to a safe place.

Generally, I think that you have to set this flag by your own will. Everywhere (therefore I did another adaption), you find failing at existing files as default. Therefore, I think the danger is not too big. I could also place a warning on startup or prompt for a confirmation before actually starting, if deletion of files is set to true. Would this be a satisfactory option?

2020-09-15 13:00 UTC, johanneshiry commented on src/main/scala/edu/ie3/simbench/io/Downloader.scala
> +          logger.warn(
I think the failing at existing files as default is sufficient.

2020-09-15 13:02 UTC, johanneshiry approved these changes

2020-09-15 13:02 UTC, merged